### PR TITLE
Reproducable dev environments with devbox

### PR DESCRIPTION
**Pull request by niklasbeinghaus**
- Add devbox
- Use devbox for testing
- Add devbox to the CI pipeline

see: #8

### CODE REVIEW

**Comment by drbacke** [comment]
I don't know devbox. No idea what it does or if it's helpfull here. Maybe someone else can look at it?

**Comment by BerndCzech** [comment]
I did not know it before and I can see why people recommend it.

What confused me was the `devbox.lock` file but this is [intentional](https://www.jetify.com/docs/devbox/quickstart/#launch-your-development-environment) (point 5.)

**Comment by niklasbeinghaus** [comment]
> Imho `contribution.md` or `readme.md` could use a first script instruction to validate the contribution, e.g. use `devbox run test` to calidate your contribution etc.

the github-ci includes the test run, so there is already a validation...

**Comment by drbacke** [comment]
Please re-run all tests, code changed quite a lot

**Pull request closed without merging**
