### PR TITLE
Extend line length

### PR DESCRIPTION
**Pull request by noootch**
This was in discussion before the big rebase.

Just line-length expansion and a simple `ruff format`

### CODE REVIEW

**Comment by noootch** [comment]
is the test broken?

**Comment by michaelosthege** [comment]
> is the test broken?

yes it's still broken on `main`

**Comment by NormannK** [comment]
> is the test broken?

yes the initial PR didnt work either

**Comment by drbacke** [comment]
Please rebase and commit again. Should Work now

**Pull request merged**
