### PR TITLE
min_soc (was killed by someone else, pls dont force push!)

### PR DESCRIPTION
**Pull request by drbacke**
- min soc for pv battery 
- unit tests corrected and tests with min_soc

### CODE REVIEW

**Comment by michaelosthege** [comment]
The whole main branch has completely new commit hashes.

When I forked EOS yesterday the [`LICENSE` was at commit ecd28cb07aef88a478b62727f94da6ca2e1434f2](https://github.com/michaelosthege/EOS/blob/main/LICENSE).
Now it's at [0591dc9dde492de02b0587dc0080a9113857e16b on main](https://github.com/Akkudoktor-EOS/EOS/commit/0591dc9dde492de02b0587dc0080a9113857e16b).

I have the main branch of before the force push locally:

image

(in other words: Looks like someone force pushed it some time between 14:32 and 15:10)

**Comment by michaelosthege** [comment]
@drbacke I pushed the old `main` branch as it was at 14:32 to [`main-at-14-32`](https://github.com/Akkudoktor-EOS/EOS/tree/main-at-14-32). You can use that to restore the original main branch if you want

**Comment by drbacke** [comment]
Thanks. Everythinh Up to Date now

**Comment by noootch** [comment]
Where my PRs closed because of this issue and they were on the old branch?

**Pull request merged**
