### PR TITLE
fix AC charge efficiency not used for price calculation

### PR DESCRIPTION
**Pull request by celle1234**
Fix bug https://github.com/Akkudoktor-EOS/EOS/issues/215

I did some tests.
The scenario is:
The first hours the price is low (10ct/kWh). Then the price rises to 20 ct/kWh. So the algorithm charges the battery in the beginning. The needed power is always 500W and there is no pv.

Here are the results:

```
# charge and discharge efficiency 100%
{"ac_charge":[0.4,0.4,1.0,0.6,0.2,0.4,0.4,0.8,0.0,0.0,0.6,0.6,0.8,0.4,0.6,1.0,1.0,1.0,0.4,0.0,0.6,0.8,1.0,0.4,0.8,0.2,0.8,0.8,0.6,1.0,0.6,1.0,0.8,0.0,0.6,0.4,0.8,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"dc_charge":[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"discharge_allowed":[0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,1,1,1,1,1,1],"eautocharge_hours_float":null,"result":{"Last_Wh_pro_Stunde":[1500.0,1500.0,3000.0,1000.0,500.0,500.0,500.0,500.0,500.0,500.0,1500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,1000.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,1000.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0],"EAuto_SoC_pro_Stunde":[60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0],"Einnahmen_Euro_pro_Stunde":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Gesamt_Verluste":0.0,"Gesamtbilanz_Euro":4.1,"Gesamteinnahmen_Euro":0.0,"Gesamtkosten_Euro":4.1,"Home_appliance_wh_per_hour":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"Kosten_Euro_pro_Stunde":[0.15,0.15,0.3,0.1,0.1,0.1,0.1,0.1,0.0,0.0,0.3,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0,0.2,0.1,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Netzbezug_Wh_pro_Stunde":[1500.0,1500.0,3000.0,1000.0,500.0,500.0,500.0,500.0,0.0,0.0,1500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,0.0,1000.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,0.0,1000.0,500.0,500.0,500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Netzeinspeisung_Wh_pro_Stunde":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Verluste_Pro_Stunde":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"akku_soc_pro_stunde":[20.0,40.0,90.0,100.0,100.0,100.0,100.0,100.0,90.0,80.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,90.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,90.0,100.0,100.0,100.0,100.0,90.0,80.0,70.0,60.0,50.0,40.0,30.0,20.0,10.0,0.0]},"eauto_obj":{"charge_array":[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"discharge_array":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"entlade_effizienz":1.0,"hours":48,"kapazitaet_wh":39000,"lade_effizienz":0.88,"max_ladeleistung_w":11000,"soc_wh":23400.0,"start_soc_prozent":100},"start_solution":[3.0,3.0,6.0,4.0,2.0,3.0,3.0,5.0,1.0,1.0,4.0,4.0,5.0,3.0,4.0,6.0,6.0,6.0,3.0,1.0,4.0,5.0,6.0,3.0,5.0,2.0,5.0,5.0,4.0,6.0,4.0,6.0,5.0,1.0,4.0,3.0,5.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"washingstart":null}
"Gesamtkosten_Euro":4.1
"Gesamt_Verluste":0.0

# charge efficiency 80% and discharge efficiency 100%
{"ac_charge":[0.2,0.8,1.0,1.0,0.8,0.6,0.0,0.4,0.8,0.8,0.8,1.0,0.6,0.4,1.0,0.8,1.0,0.0,0.2,0.8,0.4,0.4,0.8,0.0,1.0,0.2,0.2,1.0,0.4,1.0,0.6,0.4,1.0,0.6,0.0,0.8,0.2,0.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"dc_charge":[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"discharge_allowed":[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,1,1,1,1,1,1,1],"eautocharge_hours_float":null,"result":{"Last_Wh_pro_Stunde":[900.0,2100.0,2500.0,1500.0,500.0,500.0,500.0,1000.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,900.0,600.0,500.0,500.0,500.0,500.0,1000.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,1000.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0],"EAuto_SoC_pro_Stunde":[60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0],"Einnahmen_Euro_pro_Stunde":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Gesamt_Verluste":1750.0,"Gesamtbilanz_Euro":4.1,"Gesamteinnahmen_Euro":0.0,"Gesamtkosten_Euro":4.1,"Home_appliance_wh_per_hour":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"Kosten_Euro_pro_Stunde":[0.09000000000000001,0.21000000000000002,0.25,0.15,0.1,0.1,0.0,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0,0.18000000000000002,0.12000000000000001,0.1,0.1,0.1,0.0,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0,0.2,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Netzbezug_Wh_pro_Stunde":[900.0,2100.0,2500.0,1500.0,500.0,500.0,0.0,1000.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,0.0,900.0,600.0,500.0,500.0,500.0,0.0,1000.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,0.0,1000.0,500.0,500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Netzeinspeisung_Wh_pro_Stunde":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Verluste_Pro_Stunde":[100.0,400.0,500.0,250.0,0.0,0.0,0.0,125.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,25.0,0.0,0.0,0.0,0.0,125.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,125.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"akku_soc_pro_stunde":[8.0,40.0,80.0,100.0,100.0,100.0,90.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,90.0,98.0,100.0,100.0,100.0,100.0,90.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,90.0,100.0,100.0,100.0,90.0,80.0,70.0,60.0,50.0,40.0,30.0,20.0,10.0,0.0]},"eauto_obj":{"charge_array":[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"discharge_array":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"entlade_effizienz":1.0,"hours":48,"kapazitaet_wh":39000,"lade_effizienz":0.88,"max_ladeleistung_w":11000,"soc_wh":23400.0,"start_soc_prozent":100},"start_solution":[2.0,5.0,6.0,6.0,5.0,4.0,1.0,3.0,5.0,5.0,5.0,6.0,4.0,3.0,6.0,5.0,6.0,1.0,2.0,5.0,3.0,3.0,5.0,1.0,6.0,2.0,2.0,6.0,3.0,6.0,4.0,3.0,6.0,4.0,1.0,5.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"washingstart":null}
"Gesamtkosten_Euro":4.1
"Gesamt_Verluste":1750.0

# charge efficiency 100% and discharge efficiency 80%
{"ac_charge":[0.8,0.6,0.8,0.6,0.4,1.0,0.2,0.6,0.8,0.2,0.6,0.4,0.6,0.2,0.2,0.4,0.4,1.0,1.0,0.4,0.2,1.0,0.8,0.2,1.0,0.2,0.2,0.8,0.4,0.6,0.6,0.8,0.8,0.8,0.6,0.2,0.8,1.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"dc_charge":[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"discharge_allowed":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1],"eautocharge_hours_float":null,"result":{"Last_Wh_pro_Stunde":[2500.0,2000.0,2000.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0],"EAuto_SoC_pro_Stunde":[60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0],"Einnahmen_Euro_pro_Stunde":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Gesamt_Verluste":1000.0,"Gesamtbilanz_Euro":4.3,"Gesamteinnahmen_Euro":0.0,"Gesamtkosten_Euro":4.3,"Home_appliance_wh_per_hour":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"Kosten_Euro_pro_Stunde":[0.25,0.2,0.2,0.05,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1],"Netzbezug_Wh_pro_Stunde":[2500.0,2000.0,2000.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,500.0],"Netzeinspeisung_Wh_pro_Stunde":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Verluste_Pro_Stunde":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,125.0,125.0,125.0,125.0,125.0,125.0,125.0,125.0,0.0],"akku_soc_pro_stunde":[40.0,70.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,87.5,75.0,62.5,50.0,37.5,25.0,12.5,0.0,0.0]},"eauto_obj":{"charge_array":[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"discharge_array":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"entlade_effizienz":1.0,"hours":48,"kapazitaet_wh":39000,"lade_effizienz":0.88,"max_ladeleistung_w":11000,"soc_wh":23400.0,"start_soc_prozent":100},"start_solution":[5.0,4.0,5.0,4.0,3.0,6.0,2.0,4.0,5.0,2.0,4.0,3.0,4.0,2.0,2.0,3.0,3.0,6.0,6.0,3.0,2.0,6.0,5.0,2.0,6.0,2.0,2.0,5.0,3.0,4.0,4.0,5.0,5.0,5.0,4.0,2.0,5.0,6.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"washingstart":null}
"Gesamtkosten_Euro":4.3
"Gesamt_Verluste":1000.0
```

The results of test 1 and 3 are as expected, if you calculate it manually. Test 2 has the same costs as test 1, which is not possible. So I tried to fix the code like shown above.

With this i get the following result:
```
# charge efficiency 80% and discharge efficiency 100%
{"ac_charge":[0.8,1.0,0.6,0.2,1.0,0.8,0.8,0.6,0.4,0.2,1.0,1.0,0.8,0.4,0.4,0.8,0.4,0.6,0.6,0.2,0.2,0.2,0.6,0.6,0.2,0.6,0.6,0.6,0.4,0.6,0.6,0.8,1.0,1.0,0.4,0.6,0.6,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"dc_charge":[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"discharge_allowed":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1],"eautocharge_hours_float":null,"result":{"Last_Wh_pro_Stunde":[2500.0,3000.0,2000.0,750.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0],"EAuto_SoC_pro_Stunde":[60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0],"Einnahmen_Euro_pro_Stunde":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Gesamt_Verluste":1250.0,"Gesamtbilanz_Euro":4.225,"Gesamteinnahmen_Euro":0.0,"Gesamtkosten_Euro":4.225,"Home_appliance_wh_per_hour":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"Kosten_Euro_pro_Stunde":[0.25,0.3,0.2,0.075,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Netzbezug_Wh_pro_Stunde":[2500.0,3000.0,2000.0,750.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Netzeinspeisung_Wh_pro_Stunde":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Verluste_Pro_Stunde":[400.0,500.0,300.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"akku_soc_pro_stunde":[32.0,72.0,96.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,90.0,80.0,70.0,60.0,50.0,40.0,30.0,20.0,10.0,0.0]},"eauto_obj":{"charge_array":[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"discharge_array":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"entlade_effizienz":1.0,"hours":48,"kapazitaet_wh":39000,"lade_effizienz":0.88,"max_ladeleistung_w":11000,"soc_wh":23400.0,"start_soc_prozent":100},"start_solution":[5.0,6.0,4.0,2.0,6.0,5.0,5.0,4.0,3.0,2.0,6.0,6.0,5.0,3.0,3.0,5.0,3.0,4.0,4.0,2.0,2.0,2.0,4.0,4.0,2.0,4.0,4.0,4.0,3.0,4.0,4.0,5.0,6.0,6.0,3.0,4.0,4.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],"washingstart":null}
"Gesamtkosten_Euro":4.225
"Gesamt_Verluste":1250.0
```

This is the same, as when I calculate it manually.

What do you think?

I think this is one we need to fix first, before the optimization, otherwise the algorithm can not find the optimum.

### CODE REVIEW

**Comment by drbacke** [comment]
Ok for me. Maybe the checks will fail due to the new result. Could you correct them? Should be not to much work

**Comment by celle1234** [comment]
I fixed the code, which I influenced, but the battery code is as before. So what to do with these errors?

**Comment by NormannK** [comment]
error was bc of a missing dependency. it was fixed in #233
Comment to this PR: could we make a test case which so obvious results that the optimization is trivial and the numeric results can be calculated without problem by a human? This could have prevent this and future numeric problems. oc that could be done in a future PR.

**Comment by drbacke** [comment]
> error was bc of a missing dependency. it was fixed in #233 Comment to this PR: could we make a test case which so obvious results that the optimization is trivial and the numeric results can be calculated without problem by a human? This could have prevent this and future numeric problems. oc that could be done in a future PR.

Sounds very sensfull in my opinion. I will test it today on my running system.

**Pull request merged**
