### PR TITLE
Add multi-arch container build

### PR DESCRIPTION
**Pull request by ss89**
In this PR I have adjusted the dockerfile a bit, to retain some disk space.
This is the part where I am the most uncertain if I broke something, as I am not running EOS my own and just getting into the project a bit.
I did see that upon uninstalling unused packages it did uninstall the mysql/mariadb libraries, so I re-added those by tagging them as manually installed.

Also I added multi arch container image building upon release creation which then push to the github container registry and allow easier distribution of the software for docker/containerd/k8s users.

Let me know what you think or what needs adjustments to work well.

### CODE REVIEW

**Comment by ss89** [comment]
Currently I do get this error message from python, however I am not a python guy and unsure how to resolve it:
```
Traceback (most recent call last):
2024-10-03T17:34:10.780518675Z   File "/opt/eos/flask_server.py", line 19, in <module>
2024-10-03T17:34:10.780521008Z     from modules.class_optimize import isfloat, optimization_problem
2024-10-03T17:34:10.780522300Z   File "/opt/eos/modules/class_optimize.py", line 8, in <module>
2024-10-03T17:34:10.780523633Z     from modules.class_ems import EnergieManagementSystem, Wechselrichter
2024-10-03T17:34:10.780524716Z ImportError: cannot import name 'Wechselrichter' from 'modules.class_ems' (/opt/eos/modules/class_ems.py)
```

**Comment by ss89** [comment]
Fixes the trace by importing Wechselrichter from class_inverter instead of class_ems

**Comment by NormannK** [comment]
> Fixes the trace by importing Wechselrichter from class_inverter instead of class_ems

i did fix that in my PR #88

**Comment by ss89** [comment]
> > Fixes the trace by importing Wechselrichter from class_inverter instead of class_ems
> 
> i did fix that in my PR #88

Nice, i did not read through all the Forks and changes. 
There's too much work going on concurrently and I'm super new to the project.
Shouldn't be hard to fixup if needed after either of our PRs got merged 👍🏻

**Comment by ss89** [comment]
@drbacke mind checking this out?

**Pull request merged**
