### PR TITLE
Make config more flexible using env vars

### PR DESCRIPTION
**Pull request by niklasbeinghaus**
* Adds tests for config.py
* Adds support for environment variables in config.py

### CODE REVIEW

**Comment by NormannK** [comment]
i would not test for specific values in the config. the config is meant to be edited imo. 
How about checking only for the presence of the option and maybe sometimes the limits of the value.

Unless we argue this is only meant for the current dev phase and we should not touch those values

**Comment by Lasall** [comment]
Fyi: There is an extensive config overhaul here: https://github.com/Akkudoktor-EOS/EOS/pull/141 should probably put the env support on top of that.

**Comment by noootch** [comment]
> Fyi: There is an extensive config overhaul here: #141 should probably put the env support on top of that.

Yes, I'll push my final solution in a moment. And it will have env support : )

**Comment by noootch** [comment]
Ready for review :D https://github.com/Akkudoktor-EOS/EOS/pull/141

**Comment by NormannK** [comment]
all tests are working. single_test_optimization.py output is perfect. pdf looks as it should be. although we are missing the last page since some PR's

**Comment by drbacke** [comment]
Please re-run all tests, code changed quite a lot

**Comment by NormannK** [comment]
outdated, we went for json #141

**Pull request closed without merging**
