### PR TITLE
test for class_optimize in PR #88

### PR DESCRIPTION
**Pull request by NormannK**
Test meant for class_optimize.
Will only work with PR #88 since the old class has no way to use a fixed random seed.

To use it on the old/current class add `random.seed(42)` to the __init__ of  `optimization_problem` and  add `fixed_seed=None` as a possible argument.

pre-commit style of the lists and dicts does look odd.
It takes quite a while to finish also there are two warnings from the visualization class. 
Suggestions are appreciated.

### CODE REVIEW

**Comment by danimo** [comment]
can you fold this into #88 then?

**Comment by NormannK** [comment]
Sure I can, but im not so sure its the right way to do it. If you say its the proper way to do it id be happy to do so.

**Comment by danimo** [comment]
Well if the test doesn't work prior to #88, but tests #88, then it should go with #88. Maybe also rebase #88 on top of main if you know how to do so.

**Comment by NormannK** [comment]
> Well if the test doesn't work prior to #88, but tests #88, then it should go with #88. Maybe also rebase #88 on top of main if you know how to do so.

merged thanks! ill send this in to review

**Comment by drbacke** [comment]
Please merge this into the newest code, the "wechselrichter" bug is already resolved.

**Comment by michaelosthege** [comment]
that'll be
```
git fetch origin
git rebase origin/main
```

**Comment by NormannK** [comment]
thank you very much @michaelosthege I just redid my whole setup and learned a lot. i should go more smooth in the future (fingers crossed)

**Pull request merged**
